# Generated by Django 2.0.1 on 2018-01-18 18:26

from django.db import migrations


def create_fish_data(apps, schema_editor):

    Product = apps.get_model('products', 'Product')
    Category = apps.get_model('products', 'Category')

    products_data = [
        {'title': 'Macbook Air 2016', 'is_published': True, 'category_id': 1},
        {'title': 'ZenBook', 'is_published': True, 'category_id': 1},
        {'title': 'Macbook Pro 2017', 'is_published': True, 'category_id': 1},
        {'title': 'Xiaomi Redmi Pro', 'is_published': True, 'category_id': 2},
    ]

    categories_data = [
        {'title': 'Ноутбуки', 'id': 1},
        {'title': 'Мобильные телефоны', 'id': 2},
    ]

    for category in categories_data:
        Category(**category).save()

    for product in products_data:
        Product(**product).save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_fish_data),
    ]
